/* Generated By:JavaCC: Do not edit this line. eg1Constants.java */
package br.ufc.compiladores.analisadorlexico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface eg1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int NEGATE = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int OBRACKET = 12;
  /** RegularExpression Id. */
  int CBRACKET = 13;
  /** RegularExpression Id. */
  int OBRACES = 14;
  /** RegularExpression Id. */
  int CBRACES = 15;
  /** RegularExpression Id. */
  int CONSTANT = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int TVALUE = 18;
  /** RegularExpression Id. */
  int FVALUE = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int THIS = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int SYSOUT = 24;
  /** RegularExpression Id. */
  int CLASS = 25;
  /** RegularExpression Id. */
  int PUBLIC = 26;
  /** RegularExpression Id. */
  int STATIC = 27;
  /** RegularExpression Id. */
  int VOID = 28;
  /** RegularExpression Id. */
  int MAINCLASS = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int LETTER = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"boolean\"",
    "\"this\"",
    "\"new\"",
    "\"System.out.println\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "<MAINCLASS>",
    "<ID>",
    "<LETTER>",
  };

}
