/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */
package br.ufc.compiladores.analisadorlexico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int LESSTHAN = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int MULTIPLY = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int DOT = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int LBRACKET = 18;
  /** RegularExpression Id. */
  int RBRACKET = 19;
  /** RegularExpression Id. */
  int LBRACES = 20;
  /** RegularExpression Id. */
  int RBRACES = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int ULINE = 24;
  /** RegularExpression Id. */
  int PUBLIC = 25;
  /** RegularExpression Id. */
  int STATIC = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int VOID = 29;
  /** RegularExpression Id. */
  int MAIN = 30;
  /** RegularExpression Id. */
  int EXTENDS = 31;
  /** RegularExpression Id. */
  int RETURN = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int SYSOUT = 36;
  /** RegularExpression Id. */
  int CLASS = 37;
  /** RegularExpression Id. */
  int THIS = 38;
  /** RegularExpression Id. */
  int NEW = 39;
  /** RegularExpression Id. */
  int LENGTH = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int INTARRAY = 43;
  /** RegularExpression Id. */
  int BOOLEAN = 44;
  /** RegularExpression Id. */
  int LETTER = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int INT_LITERAL = 47;
  /** RegularExpression Id. */
  int ID = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"+\"",
    "\"&&\"",
    "\"<\"",
    "\"-\"",
    "\"*\"",
    "\"!\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"_\"",
    "\"public\"",
    "\"static\"",
    "\"true\"",
    "\"false\"",
    "\"void\"",
    "\"main\"",
    "\"extends\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"System.out.println\"",
    "\"class\"",
    "\"this\"",
    "\"new\"",
    "\"length\"",
    "\"String\"",
    "\"int\"",
    "\"int[]\"",
    "\"boolean\"",
    "<LETTER>",
    "<DIGIT>",
    "<INT_LITERAL>",
    "<ID>",
  };

}
